import os,sys 
os.system('clear')
print('\n Update Di Mulai mohon tunggu.....')
os.system('sleep 2')
os.system('pip install requests')
print('Install Requests Selsai √')
os.system('sleep 2')
os.system('pip install mechanize')
print ('Install Mechanize Seleai √')
os.system('sleep 2 ')
os.system('pip install bs4')
print ('Installl Bs4 Selesi √')
os.system('mv gg.py .ig.py')
os.system('rm -rf install.py')
os.system('sleep 2')
print('selesai update √')
